/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package finalproject;

import javax.swing.DefaultListModel;
import java.sql.*;
/**
 *
 * @author annab
 */
public class GeneralMed extends javax.swing.JFrame {

    String console = "";
    int id;
    Connection con;
    PreparedStatement pst;
    ResultSet rs;
    /**
     * Creates new form GeneralMed
     */
    public GeneralMed() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        generalID = new javax.swing.JTextField();
        IDpatient = new javax.swing.JTextField();
        tobaccoField = new javax.swing.JTextField();
        tobaccoQuantityField = new javax.swing.JTextField();
        tobaccoDurationField = new javax.swing.JTextField();
        alcoholField = new javax.swing.JTextField();
        alcoholQuantityField = new javax.swing.JTextField();
        alcoholDurationField = new javax.swing.JTextField();
        drugsField = new javax.swing.JTextField();
        drugsDurationField = new javax.swing.JTextField();
        bloodTypeField = new javax.swing.JTextField();
        rhFactorField = new javax.swing.JTextField();
        genEditButton = new javax.swing.JButton();
        genSaveButton = new javax.swing.JButton();
        genDeleteButton = new javax.swing.JButton();
        genCloseButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        generalList = new javax.swing.JList<>();
        loadHistory = new javax.swing.JButton();
        drugTypeField = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        generalEvents = new javax.swing.JTextArea();
        outdated = new javax.swing.JCheckBox();
        jLabel16 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("General Medical History");

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setText("Start Interview");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("General Medical History ID:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Patient ID:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Tobacco (Yes/No):");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Tobacco Quantity:");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Tobacco Duration:");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("Alcohol (Yes/No):");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setText("Alcohol Quantity:");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setText("Alcohol Duration:");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setText("Drugs (Yes/No):");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel11.setText("Blood Type:");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel12.setText("Drug/s Duration:");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel13.setText("Rh:");

        generalID.setEditable(false);

        IDpatient.setEditable(false);
        IDpatient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IDpatientActionPerformed(evt);
            }
        });

        tobaccoField.setEnabled(false);

        tobaccoQuantityField.setEnabled(false);

        tobaccoDurationField.setEnabled(false);

        alcoholField.setEnabled(false);

        alcoholQuantityField.setEnabled(false);

        alcoholDurationField.setEnabled(false);

        drugsField.setEnabled(false);
        drugsField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                drugsFieldActionPerformed(evt);
            }
        });

        drugsDurationField.setEnabled(false);

        bloodTypeField.setEnabled(false);

        rhFactorField.setEnabled(false);

        genEditButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        genEditButton.setText("Edit");
        genEditButton.setEnabled(false);
        genEditButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                genEditButtonActionPerformed(evt);
            }
        });

        genSaveButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        genSaveButton.setText("Save");
        genSaveButton.setEnabled(false);
        genSaveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                genSaveButtonActionPerformed(evt);
            }
        });

        genDeleteButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        genDeleteButton.setText("Delete");
        genDeleteButton.setEnabled(false);
        genDeleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                genDeleteButtonActionPerformed(evt);
            }
        });

        genCloseButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        genCloseButton.setText("Close");
        genCloseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                genCloseButtonActionPerformed(evt);
            }
        });

        generalList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                generalListValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(generalList);

        loadHistory.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        loadHistory.setText("Load General History");
        loadHistory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadHistoryActionPerformed(evt);
            }
        });

        drugTypeField.setEnabled(false);

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel14.setText("Drug/s Type:");

        generalEvents.setEditable(false);
        generalEvents.setColumns(20);
        generalEvents.setRows(5);
        jScrollPane2.setViewportView(generalEvents);

        outdated.setEnabled(false);

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel16.setText("Is Outdated?");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel14)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(drugTypeField, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(bloodTypeField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
                                .addComponent(drugsDurationField, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(alcoholField)
                                .addComponent(generalID, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(IDpatient, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(tobaccoField, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(tobaccoQuantityField, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(tobaccoDurationField, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(alcoholQuantityField)
                                .addComponent(alcoholDurationField)
                                .addComponent(drugsField))
                            .addComponent(rhFactorField, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(genDeleteButton, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE)
                                        .addComponent(genCloseButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(genEditButton, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(genSaveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(67, 67, 67)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addContainerGap(42, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(loadHistory)
                                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(42, 42, 42))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(331, 331, 331))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(outdated)
                        .addGap(60, 60, 60))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(26, 26, 26)
                .addComponent(jButton1)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(generalID, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(IDpatient, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(tobaccoField, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5)
                                    .addComponent(tobaccoQuantityField, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6)
                                    .addComponent(tobaccoDurationField, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel7)
                                    .addComponent(alcoholField, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel8)
                                    .addComponent(alcoholQuantityField, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel9)
                                    .addComponent(alcoholDurationField, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(loadHistory)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(drugsField, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(drugsDurationField, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(genEditButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(genSaveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(genDeleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(genCloseButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(jLabel14))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(drugTypeField, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(bloodTypeField, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(rhFactorField, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(outdated)
                            .addComponent(jLabel16))
                        .addGap(25, 25, 25))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void genDeleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_genDeleteButtonActionPerformed
        // TODO add your handling code here:
                //get patient ID
        int gID = Integer.parseInt(generalID.getText());
        try {
            //connect and prepare delete statement for database
            con = connections.getConnection();
            pst = con.prepareStatement("DELETE FROM generalmedicalhistorytable WHERE GeneralMedicalHistoryID=?");
            //set ID equal to ?
            pst.setObject(1, gID);
            //execute the query
            pst.execute();
            
            //terminal at bottom
            System.out.println("Deleted General Medical History successfully :D");
            java.util.Date date = new java.util.Date();
            console += date + ": Deleted General Medical History successfully :D\n\t---You can now refresh the list.";
            generalEvents.setText(console);
            
        } catch(Exception ex) {
            //terminal at bottom
            System.out.println("Failed to delete allergy :(");
            System.err.println(ex.getMessage());
            java.util.Date date = new java.util.Date();
            console += date + ": " + gID + " Failed to delete General Medical History :(\n";
            generalEvents.setText(console);
            
        }
        
        genSaveButton.setEnabled(false);
        genDeleteButton.setEnabled(false);
        tobaccoField.setEnabled(false);
        tobaccoDurationField.setEnabled(false);
        tobaccoQuantityField.setEnabled(false);
        alcoholField.setEnabled(false);
        alcoholDurationField.setEnabled(false);
        alcoholQuantityField.setEnabled(false);
        drugsField.setEnabled(false);
        drugsDurationField.setEnabled(false);
        drugTypeField.setEnabled(false);
        bloodTypeField.setEnabled(false);
        rhFactorField.setEnabled(false);
    }//GEN-LAST:event_genDeleteButtonActionPerformed

    private void genCloseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_genCloseButtonActionPerformed
        // TODO add your handling code here:
        
        int patID = Integer.parseInt(IDpatient.getText());
        PatientDemographicForm frame6 = new PatientDemographicForm();
        String change = Integer.toString(patID);
        PatientDemographicForm.idField.setText(change);
        
        try {
            con = connections.getConnection();
            pst = con.prepareStatement("Select * From patienttable where PatientID = ?");
            pst.setObject(1, patID);
            rs = pst.executeQuery();
            
            String lName = "";
            String plName = "";
            String fName = "";
            String address1 = "";
            String address2 = "";
            String city = "";
            String state = "";
            String zip = "";
            String country = "";
            String citizen = "";
            String phone = "";
            String emergencyPhone = "";
            String email = "";
            String ssn = "";
            String dob = "";
            String gender = "";
            String ethnic = "";
            String marital = "";
            String hcp = "";
            int active = 0;
            String comment = "";
            String sub = "";
            String nextKin = "";
            String mi = "";
            String nextKinRelation = "";

            while(rs.next()) {
                
                //set strings to equal values drawn from database
                lName = rs.getString("PtLastName");
                plName = rs.getString("PtPreviousLastName");
                fName = rs.getString("PtFirstName");
                address1 = rs.getString("HomeAddress1");
                address2 = rs.getString("HomeAddress2");
                city = rs.getString("HomeCity");
                state = rs.getString("HomeState");
                zip = rs.getString("HomeZip");
                country = rs.getString("Country");
                citizen = rs.getString("Citizenship");
                phone = rs.getString("PtHomePhone");
                emergencyPhone = rs.getString("EmergencyPhoneNumber");
                email = rs.getString("EmailAddress");
                ssn = rs.getString("PtSSN");
                dob = rs.getString("DOB");
                gender = rs.getString("Gender");
                ethnic = rs.getString("EthnicAssociation");
                marital = rs.getString("MaritalStatus");
                hcp = rs.getString("CurrentPrimaryHCPId");
                active = rs.getInt("Active");
                comment = rs.getString("Comments");
                sub = rs.getString("SubscriberRelationship");
                nextKin = rs.getString("NextOfKin");
                mi = rs.getString("PtMiddleInitial");
                nextKinRelation = rs.getString("NextOfKinRelationshipToPatient");
                
                
            }
            
            //send over values from strings to patientdemographic form text boxes
            PatientDemographicForm.lName.setText(lName);
            PatientDemographicForm.plName.setText(plName);
            PatientDemographicForm.fName.setText(fName);
            PatientDemographicForm.address1.setText(address1);
            PatientDemographicForm.address2.setText(address2);
            PatientDemographicForm.city.setText(city);
            PatientDemographicForm.state.setText(state);
            PatientDemographicForm.zip.setText(zip);
            PatientDemographicForm.country.setText(country);
            PatientDemographicForm.citizen.setText(citizen);
            PatientDemographicForm.phone.setText(phone);
            PatientDemographicForm.emergencyPhone.setText(emergencyPhone);
            PatientDemographicForm.email.setText(email);
            PatientDemographicForm.ssn.setText(ssn);
            PatientDemographicForm.dob.setText(dob);
            PatientDemographicForm.gender.setText(gender);
            PatientDemographicForm.ethnic.setText(ethnic);
            PatientDemographicForm.marital.setText(marital);
            PatientDemographicForm.hcp.setText(hcp);
            PatientDemographicForm.middle.setText(mi);
            PatientDemographicForm.comments.setText(comment);
            PatientDemographicForm.subscriber.setText(sub);
            PatientDemographicForm.kin.setText(nextKin);
            PatientDemographicForm.kinRelationship.setText(nextKinRelation);
            
            //check what active equals and set check box based on 0 - 1 values
            if(active == 1) {
                PatientDemographicForm.active.setSelected(true);
            }
            else if (active == 0)
            {
                PatientDemographicForm.active.setSelected(false);
            }
        }
        catch(Exception E)
        {
            //if can't connect to database or something mistyped
            System.out.println("Did not succeed. :<");
            java.util.Date date = new java.util.Date();
            console += date + ": Failed to close :(\n";
            generalEvents.setText(console);
        }
        
        frame6.setVisible(true);
        this.setVisible(false);

    }//GEN-LAST:event_genCloseButtonActionPerformed

    private void drugsFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_drugsFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_drugsFieldActionPerformed

    private void IDpatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IDpatientActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IDpatientActionPerformed

    private void loadHistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadHistoryActionPerformed
        // TODO add your handling code here:
        
        DefaultListModel general = new DefaultListModel();
        try {
            
            //grab all patients from database
            con = connections.getConnection();
            pst = con.prepareStatement("SELECT * from generalmedicalhistorytable WHERE PatientID=?;");
            pst.setObject(1, Integer.parseInt(IDpatient.getText()));
            rs = pst.executeQuery();
            
            while(rs.next()) {
                int gID = rs.getInt("GeneralMedicalHistoryID");
                String fullString = gID + "  ---  " + IDpatient.getText();
                general.addElement(fullString);
            }
            generalList.setModel(general);
            
            java.util.Date date = new java.util.Date();
            console += date + ": General List Loaded Successfully! :D\n";
            generalEvents.setText(console);
        }
        catch(Exception e) {
            
            System.out.println("Could not connect successfully! :<");
            java.util.Date date = new java.util.Date();
            console += date + ": Failed to connect :(\n";
            generalEvents.setText(console);
        }
        
    }//GEN-LAST:event_loadHistoryActionPerformed

    private void generalListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_generalListValueChanged
        // TODO add your handling code here:
        String value = generalList.getSelectedValue();
        System.out.println(value);
        char f = value.charAt(0);
        int newGeneralID = Integer.parseInt(String.valueOf(f));
        
        String genID = Integer.toString(newGeneralID);
        generalID.setText(genID);
        
        genEditButton.setEnabled(true);
        
        
        String tobacco;
        String tQuan;
        String tDur;
        String alcohol;
        String aQuan;
        String aDur;
        String drug;
        String dType;
        String dDur;
        String btype;
        String rh;
        int del;
        
        try {
            
            con = connections.getConnection();
            pst = con.prepareStatement("SELECT * from `generalmedicalhistorytable` WHERE `GeneralMedicalHistoryID`=?;");
            pst.setObject(1, newGeneralID);
            rs = pst.executeQuery();
            
            while(rs.next()) {
                
                tobacco = rs.getString("Tobacco");
                tQuan = rs.getString("TobaccoQuantity");
                tDur = rs.getString("Tobaccoduration");
                alcohol = rs.getString("Alcohol");
                aQuan = rs.getString("AlcoholQuantity");
                aDur = rs.getString("Alcoholduration");
                drug = rs.getString("Drug");
                dType = rs.getString("DrugType");
                dDur = rs.getString("Drugduration");
                btype = rs.getString("BloodType");
                rh = rs.getString("Rh");
                del = rs.getInt("deleted");
                
                tobaccoField.setText(tobacco);
                tobaccoQuantityField.setText(tQuan);
                tobaccoDurationField.setText(tDur);
                
                alcoholField.setText(alcohol);
                alcoholQuantityField.setText(aQuan);
                alcoholDurationField.setText(aDur);
                
                drugsField.setText(drug);
                drugTypeField.setText(dType);
                drugsDurationField.setText(dDur);
                
                bloodTypeField.setText(btype);
                rhFactorField.setText(rh);
                
                
                if(del == 0) {
                    outdated.setSelected(false);
                }
                else if (del == 1)
                {
                    outdated.setSelected(true);
                }
                
            }
            
            
            
        }
        catch(Exception e) {
            
            System.out.println("Could not connect successfully! :<");
            java.util.Date date = new java.util.Date();
            console += date + ": Failed to connect :(\n";
            generalEvents.setText(console);
        }
    }//GEN-LAST:event_generalListValueChanged

    private void genEditButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_genEditButtonActionPerformed
        // TODO add your handling code here:
        genSaveButton.setEnabled(true);
        genEditButton.setEnabled(false);
        genDeleteButton.setEnabled(true);
        outdated.setEnabled(true);
        
        tobaccoField.setEnabled(true);
        tobaccoDurationField.setEnabled(true);
        tobaccoQuantityField.setEnabled(true);
        alcoholField.setEnabled(true);
        alcoholDurationField.setEnabled(true);
        alcoholQuantityField.setEnabled(true);
        drugsField.setEnabled(true);
        drugsDurationField.setEnabled(true);
        drugTypeField.setEnabled(true);
        bloodTypeField.setEnabled(true);
        rhFactorField.setEnabled(true);
    }//GEN-LAST:event_genEditButtonActionPerformed

    private void genSaveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_genSaveButtonActionPerformed
        // TODO add your handling code here:
        
        int genID = Integer.parseInt(generalID.getText());
        
        String tobacco = tobaccoField.getText();
        String tQuan = tobaccoQuantityField.getText();
        String tDur = tobaccoDurationField.getText();
        String alcohol = alcoholField.getText();
        String aQuan = alcoholQuantityField.getText();
        String aDur = alcoholDurationField.getText();
        String drug = drugsField.getText();
        String dType = drugTypeField.getText();
        String dDur = drugsDurationField.getText();
        String btype = bloodTypeField.getText();
        String rh = rhFactorField.getText();
        int dele;
        
        if (outdated.isSelected()) {
            dele = 1;
        }
        else {
            dele = 0;
        }
        
        try {
            con = connections.getConnection();
                
            //set up prepared update query
            pst = con.prepareStatement("UPDATE generalmedicalhistorytable SET Tobacco=?, TobaccoQuantity=?, "
                + "Tobaccoduration=?, Alcohol=?, AlcoholQuantity=?, Alcoholduration=?, Drug=?, "
                + "DrugType=?, Drugduration=?, BloodType=?, Rh=?, deleted=? WHERE GeneralMedicalHistoryID=?");
                
            //set values for update query based on text box data inputted
            pst.setString(1, tobacco);
            pst.setString(2, tQuan);
            pst.setString(3, tDur);
            pst.setString(4, alcohol);
            pst.setString(5, aQuan);
            pst.setString(6, aDur);
            pst.setString(7, drug);
            pst.setString(8, dType);
            pst.setString(9, dDur);
            pst.setString(10, btype);
            pst.setString(11, rh);
            pst.setInt(12, dele);
            
            pst.setObject(13, genID);
            //execute query
            pst.execute();
                
            //terminal at bottom
            java.util.Date date = new java.util.Date();
            System.out.println("Saved General Med History successfully! :D");
            console += date + ": Saved General Med History successfully! :D\n";
            generalEvents.setText(console);
            
        } catch (Exception ex) {
            //terminal at bottom
            java.util.Date date = new java.util.Date();
            console += date + ": Failed to save General Med History :<\n";
            System.out.println("Failed to save General Med History :<");
            generalEvents.setText(console);
        }
        
        
        genSaveButton.setEnabled(false);
        genDeleteButton.setEnabled(false);
        outdated.setEnabled(false);
        genEditButton.setEnabled(true);
        
        tobaccoField.setEnabled(false);
        tobaccoDurationField.setEnabled(false);
        tobaccoQuantityField.setEnabled(false);
        alcoholField.setEnabled(false);
        alcoholDurationField.setEnabled(false);
        alcoholQuantityField.setEnabled(false);
        drugsField.setEnabled(false);
        drugsDurationField.setEnabled(false);
        drugTypeField.setEnabled(false);
        bloodTypeField.setEnabled(false);
        rhFactorField.setEnabled(false);
        
        
    }//GEN-LAST:event_genSaveButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GeneralMed.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GeneralMed.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GeneralMed.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GeneralMed.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GeneralMed().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JTextField IDpatient;
    public static javax.swing.JTextField alcoholDurationField;
    public static javax.swing.JTextField alcoholField;
    public static javax.swing.JTextField alcoholQuantityField;
    public static javax.swing.JTextField bloodTypeField;
    public static javax.swing.JTextField drugTypeField;
    public static javax.swing.JTextField drugsDurationField;
    public static javax.swing.JTextField drugsField;
    private javax.swing.JButton genCloseButton;
    private javax.swing.JButton genDeleteButton;
    private javax.swing.JButton genEditButton;
    private javax.swing.JButton genSaveButton;
    private javax.swing.JTextArea generalEvents;
    public static javax.swing.JTextField generalID;
    private javax.swing.JList<String> generalList;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton loadHistory;
    private javax.swing.JCheckBox outdated;
    public static javax.swing.JTextField rhFactorField;
    public static javax.swing.JTextField tobaccoDurationField;
    public static javax.swing.JTextField tobaccoField;
    public static javax.swing.JTextField tobaccoQuantityField;
    // End of variables declaration//GEN-END:variables
}
