/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package finalproject;

/**
 *
 * @author annab
 */
import java.sql.*;
 

public class PatientDemographicForm extends javax.swing.JFrame {
    
    //set up global variables for form
    String console = "";
    Connection con;
    PreparedStatement pst;
    ResultSet rs;
    static boolean isNew = false;
    /**
     * Creates new form PatientDemographicForm
     */
    public PatientDemographicForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        lName = new javax.swing.JTextField();
        plName = new javax.swing.JTextField();
        fName = new javax.swing.JTextField();
        address1 = new javax.swing.JTextField();
        address2 = new javax.swing.JTextField();
        city = new javax.swing.JTextField();
        state = new javax.swing.JTextField();
        zip = new javax.swing.JTextField();
        country = new javax.swing.JTextField();
        citizen = new javax.swing.JTextField();
        emergencyPhone = new javax.swing.JTextField();
        phone = new javax.swing.JTextField();
        dob = new javax.swing.JTextField();
        ssn = new javax.swing.JTextField();
        middle = new javax.swing.JTextField();
        email = new javax.swing.JTextField();
        ethnic = new javax.swing.JTextField();
        gender = new javax.swing.JTextField();
        marital = new javax.swing.JTextField();
        hcp = new javax.swing.JTextField();
        kin = new javax.swing.JTextField();
        kinRelationship = new javax.swing.JTextField();
        subscriber = new javax.swing.JTextField();
        allergyButton = new javax.swing.JButton();
        generalMedicalButton = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        newButton = new javax.swing.JButton();
        editButton = new javax.swing.JButton();
        saveButton = new javax.swing.JButton();
        deletedButton = new javax.swing.JButton();
        closeButton = new javax.swing.JButton();
        jLabel26 = new javax.swing.JLabel();
        comments = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        active = new javax.swing.JCheckBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        events = new javax.swing.JTextArea();
        idField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Patient Demographic Form");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Patient ID:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Last Name:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Date of Birth:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Previous Last Name:");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("First Name:");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("Address 1:");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setText("Address 2:");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setText("City:");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setText("State:");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel11.setText("Zipcode:");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel12.setText("Country:");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel13.setText("Citizenship:");

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel14.setText("Home Phone:");

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel15.setText("Emergency Phone:");

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel16.setText("SSN:");

        jLabel17.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel17.setText("Email Address:");

        jLabel18.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel18.setText("Gender:");

        jLabel19.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel19.setText("Ethnic Association:");

        jLabel20.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel20.setText("Marital Status:");

        jLabel21.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel21.setText("Current Primary HC PID:");

        jLabel22.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel22.setText("Middle Initial:");

        jLabel23.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel23.setText("Next of Kin:");

        jLabel24.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel24.setText("Next of Kin Relationship:");

        jLabel25.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel25.setText("Subscriber Relationship:");

        lName.setEnabled(false);

        plName.setEnabled(false);
        plName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plNameActionPerformed(evt);
            }
        });

        fName.setEnabled(false);

        address1.setEnabled(false);

        address2.setEnabled(false);

        city.setEnabled(false);
        city.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cityActionPerformed(evt);
            }
        });

        state.setEnabled(false);

        zip.setEnabled(false);

        country.setEnabled(false);

        citizen.setEnabled(false);

        emergencyPhone.setEnabled(false);

        phone.setEnabled(false);

        dob.setText("MM/DD/YYYY");
        dob.setEnabled(false);

        ssn.setText("***-***-****");
        ssn.setEnabled(false);

        middle.setEnabled(false);

        email.setEnabled(false);

        ethnic.setEnabled(false);

        gender.setEnabled(false);

        marital.setEnabled(false);
        marital.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maritalActionPerformed(evt);
            }
        });

        hcp.setEnabled(false);

        kin.setEnabled(false);

        kinRelationship.setEnabled(false);

        subscriber.setEnabled(false);

        allergyButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        allergyButton.setText("Allergy History");
        allergyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                allergyButtonActionPerformed(evt);
            }
        });

        generalMedicalButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        generalMedicalButton.setText("General  Medical History");
        generalMedicalButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generalMedicalButtonActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton3.setText("New");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        newButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        newButton.setText("New");
        newButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newButtonActionPerformed(evt);
            }
        });

        editButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        editButton.setText("Edit");
        editButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editButtonActionPerformed(evt);
            }
        });

        saveButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        saveButton.setText("Save");
        saveButton.setEnabled(false);
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        deletedButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        deletedButton.setText("Delete");
        deletedButton.setEnabled(false);
        deletedButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletedButtonActionPerformed(evt);
            }
        });

        closeButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        closeButton.setText("Close");
        closeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeButtonActionPerformed(evt);
            }
        });

        jLabel26.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel26.setText("Comments:");

        comments.setEnabled(false);
        comments.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                commentsActionPerformed(evt);
            }
        });

        jLabel27.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel27.setText("Active:");

        active.setText("Alive?");
        active.setEnabled(false);

        events.setEditable(false);
        events.setColumns(20);
        events.setRows(5);
        jScrollPane1.setViewportView(events);

        idField.setEditable(false);
        idField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addGap(66, 66, 66)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lName)
                                    .addComponent(idField)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel15))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(plName)
                                    .addComponent(fName)
                                    .addComponent(address1)
                                    .addComponent(address2)
                                    .addComponent(city)
                                    .addComponent(state)
                                    .addComponent(zip)
                                    .addComponent(country)
                                    .addComponent(citizen)
                                    .addComponent(phone)
                                    .addComponent(emergencyPhone)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(newButton)
                                .addGap(18, 18, 18)
                                .addComponent(editButton)
                                .addGap(18, 18, 18)
                                .addComponent(deletedButton)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(closeButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(saveButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(allergyButton)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(generalMedicalButton)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton3))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel22)
                                            .addComponent(jLabel17)
                                            .addComponent(jLabel18)
                                            .addComponent(jLabel19)
                                            .addComponent(jLabel20)
                                            .addComponent(jLabel21)
                                            .addComponent(jLabel24)
                                            .addComponent(jLabel23)
                                            .addComponent(jLabel25)
                                            .addComponent(jLabel26)
                                            .addComponent(jLabel27))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(middle, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                                                    .addComponent(email)
                                                    .addComponent(ssn, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                                                    .addComponent(dob)))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(40, 40, 40)
                                                .addComponent(active))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(comments, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
                                                    .addComponent(subscriber, javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(kinRelationship, javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(gender, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(ethnic, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(marital, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(hcp, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(kin, javax.swing.GroupLayout.Alignment.TRAILING)))))
                                    .addComponent(jLabel16)
                                    .addComponent(jLabel4)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(273, 273, 273)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 574, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(dob, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(idField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16)
                    .addComponent(ssn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(plName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(middle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(fName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17)
                    .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jLabel18))
                        .addComponent(gender))
                    .addComponent(address1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(address2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19)
                    .addComponent(ethnic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(active))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(marital, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel9)
                        .addComponent(city, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel20)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(state, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21)
                    .addComponent(hcp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(zip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23)
                    .addComponent(kin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(country, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(4, 4, 4))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel24)
                            .addComponent(kinRelationship, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(subscriber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel13)
                        .addComponent(citizen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel25)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel14)
                        .addComponent(phone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(comments, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel26))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(17, 17, 17))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel15)
                                    .addComponent(emergencyPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(allergyButton)
                                .addGap(3, 3, 3)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(saveButton)
                            .addComponent(closeButton)
                            .addComponent(deletedButton)
                            .addComponent(editButton)
                            .addComponent(newButton)
                            .addComponent(generalMedicalButton))))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void maritalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maritalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_maritalActionPerformed

    private void plNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_plNameActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void newButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newButtonActionPerformed
        // TODO add your handling code here:
        
        //set isNew to true so Save button functions correctly
        isNew = true;
        
        //set up buttons, enabled or disabled to prevent error
        saveButton.setEnabled(true);
        deletedButton.setEnabled(false);
        newButton.setEnabled(false);
        editButton.setEnabled(false);
        allergyButton.setEnabled(false);
        generalMedicalButton.setEnabled(false);
        //set text fields to editable
        lName.setEnabled(true);
        fName.setEnabled(true);
        middle.setEnabled(true);
        plName.setEnabled(true);
        address1.setEnabled(true);
        address2.setEnabled(true);
        email.setEnabled(true);
        dob.setEnabled(true);
        ssn.setEnabled(true);
        hcp.setEnabled(true);
        ethnic.setEnabled(true);
        subscriber.setEnabled(true);
        kin.setEnabled(true);
        kinRelationship.setEnabled(true);
        phone.setEnabled(true);
        emergencyPhone.setEnabled(true);
        comments.setEnabled(true);
        gender.setEnabled(true);
        city.setEnabled(true);
        state.setEnabled(true);
        zip.setEnabled(true);
        country.setEnabled(true);
        citizen.setEnabled(true);
        marital.setEnabled(true);
        active.setEnabled(true);
        
        
        //set default text values for new form
        idField.setText("");
        lName.setText("");
        fName.setText("");
        middle.setText("");
        plName.setText("");
        address1.setText("");
        address2.setText("");
        email.setText("");
        dob.setText("MM/DD/YYYY");
        ssn.setText("***-**-****");
        hcp.setText("");
        ethnic.setText("");
        subscriber.setText("");
        kin.setText("");
        kinRelationship.setText("");
        phone.setText("###-###-####");
        emergencyPhone.setText("###-###-####");
        comments.setText("");
        gender.setText("");
        city.setText("");
        state.setText("");
        zip.setText("");
        country.setText("");
        citizen.setText("");
        marital.setText("");
    }//GEN-LAST:event_newButtonActionPerformed

    private void editButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editButtonActionPerformed
        // TODO add your handling code here:
        
        //set up, not new patient, for Save button
        isNew = false;
        
        //set buttons enabled
        deletedButton.setEnabled(true);
        saveButton.setEnabled(true);
        
        //set fields editable
        lName.setEnabled(true);
        fName.setEnabled(true);
        middle.setEnabled(true);
        plName.setEnabled(true);
        address1.setEnabled(true);
        address2.setEnabled(true);
        email.setEnabled(true);
        dob.setEnabled(true);
        ssn.setEnabled(true);
        hcp.setEnabled(true);
        ethnic.setEnabled(true);
        subscriber.setEnabled(true);
        kin.setEnabled(true);
        kinRelationship.setEnabled(true);
        phone.setEnabled(true);
        emergencyPhone.setEnabled(true);
        comments.setEnabled(true);
        gender.setEnabled(true);
        city.setEnabled(true);
        state.setEnabled(true);
        zip.setEnabled(true);
        country.setEnabled(true);
        citizen.setEnabled(true);
        marital.setEnabled(true);
        active.setEnabled(true);
    }//GEN-LAST:event_editButtonActionPerformed

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        // TODO add your handling code here:
        
        //if not new patient form, just editing current
        if (Boolean.valueOf(isNew)==false) {
            int alive = 1;

            //convert checkbox to 1 or 0 value
            if(active.isSelected()) {
                alive = 1;
            }
            else {
                alive = 0;
            }
            try {
                
                //get ID
                int pID = Integer.parseInt(idField.getText());
                
                con = connections.getConnection();
                
                //set up prepared update query
                pst = con.prepareStatement("UPDATE patienttable SET PtLastName=?, PtPreviousLastName=?, "
                        + "PtFirstName=?, HomeAddress1=?, HomeAddress2=?, HomeCity=?, "
                        + "HomeState=?, HomeZip=?, Country=?, Citizenship=?, PtHomePhone=?, "
                        + "EmergencyPhoneNumber=?, EmailAddress=?, PtSSN=?, DOB=?, Gender=?, "
                        + "EthnicAssociation=?, MaritalStatus=?, CurrentPrimaryHCPId=?, "
                        + "Active=?, Comments=?, SubscriberRelationship=?, NextOfKin=?, PtMiddleInitial=?, "
                        + "NextOfKinRelationshipToPatient=? WHERE PatientID=?");
                
                //set values for update query based on text box data inputted
                pst.setString(1, lName.getText());
                pst.setString(2, plName.getText());
                pst.setString(3, fName.getText());
                pst.setString(4, address1.getText());
                pst.setString(5, address2.getText());
                pst.setString(6, city.getText());
                pst.setString(7, state.getText());
                pst.setString(8, zip.getText());
                pst.setString(9, country.getText());
                pst.setString(10, citizen.getText());
                pst.setString(11, phone.getText());
                pst.setString(12, emergencyPhone.getText());
                pst.setString(13, email.getText());
                pst.setString(14, ssn.getText());
                pst.setString(15, dob.getText());
                pst.setString(16, gender.getText());
                pst.setString(17, ethnic.getText());
                pst.setString(18, marital.getText());
                pst.setString(19, hcp.getText());
                pst.setInt(20, alive);
                pst.setString(21, comments.getText());
                pst.setString(22, subscriber.getText());
                pst.setString(23, kin.getText());
                pst.setString(24, middle.getText());
                pst.setString(25, kinRelationship.getText());
                pst.setObject(26, pID);
                
                //execute query
                pst.execute();
                
                //terminal at bottom
                java.util.Date date = new java.util.Date();
                System.out.println("Saved successfully! :D");
                console += date + ": Saved successfully! :D\n";
                events.setText(console);
            
            } catch (Exception ex) {
                //terminal at bottom
                java.util.Date date = new java.util.Date();
                console += date + ": Failed to save :<\n";
                System.out.println("Failed to save :<");
                events.setText(console);
            }
        }
        //else if it is a new patient
        else {
            try {
                int alive = 1;

                //convert check box to 1 or 0
                if(active.isSelected()) {
                    alive = 1;
                }
                else {
                    alive = 0;
                }
                con = connections.getConnection();
                //prepare statement for inserting new patient
                pst = con.prepareStatement("INSERT INTO `patienttable`(`PtLastName`, `PtPreviousLastName`, `PtFirstName`, `HomeAddress1`, `HomeAddress2`, `HomeCity`, `HomeState`, `HomeZip`, `Country`, `Citizenship`, `PtHomePhone`, `EmergencyPhoneNumber`, `EmailAddress`, `PtSSN`, `DOB`, `Gender`, `EthnicAssociation`, `MaritalStatus`, `CurrentPrimaryHCPId`, `Active`, `Comments`, `SubscriberRelationship`, `NextOfKin`, `PtMiddleInitial`, `NextOfKinRelationshipToPatient`) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)");
                
                //set values based on what is inputted in text boxes
                pst.setString(1, lName.getText());
                pst.setString(2, plName.getText());
                pst.setString(3, fName.getText());
                pst.setString(4, address1.getText());
                pst.setString(5, address2.getText());
                pst.setString(6, city.getText());
                pst.setString(7, state.getText());
                pst.setString(8, zip.getText());
                pst.setString(9, country.getText());
                pst.setString(10, citizen.getText());
                pst.setString(11, phone.getText());
                pst.setString(12, emergencyPhone.getText());
                pst.setString(13, email.getText());
                pst.setString(14, ssn.getText());
                pst.setString(15, dob.getText());
                pst.setString(16, gender.getText());
                pst.setString(17, ethnic.getText());
                pst.setString(18, marital.getText());
                pst.setString(19, hcp.getText());
                pst.setInt(20, alive);
                pst.setString(21, comments.getText());
                pst.setString(22, subscriber.getText());
                pst.setString(23, kin.getText());
                pst.setString(24, middle.getText());
                pst.setString(25, kinRelationship.getText());
                
                //execute query
                pst.execute();
                
                //terminal at bottom
                java.util.Date date = new java.util.Date();
                System.out.println("Saved new patient successfully! :D");
                console += date + ": Saved new patient successfully! :D\n";
                events.setText(console);
            
            } catch (Exception ex) {
                
                //terminal at bottom
                java.util.Date date = new java.util.Date();
                console += date + ": Failed to save new patient :<\n";
                System.out.println("Failed to save :<");
                events.setText(console);
            }
        }
        
        //after button is clicked, form will default back to original settings
        saveButton.setEnabled(false);
        lName.setEnabled(false);
        fName.setEnabled(false);
        middle.setEnabled(false);
        plName.setEnabled(false);
        address1.setEnabled(false);
        address2.setEnabled(false);
        email.setEnabled(false);
        dob.setEnabled(false);
        ssn.setEnabled(false);
        hcp.setEnabled(false);
        ethnic.setEnabled(false);
        subscriber.setEnabled(false);
        kin.setEnabled(false);
        kinRelationship.setEnabled(false);
        phone.setEnabled(false);
        emergencyPhone.setEnabled(false);
        comments.setEnabled(false);
        gender.setEnabled(false);
        city.setEnabled(false);
        state.setEnabled(false);
        zip.setEnabled(false);
        country.setEnabled(false);
        citizen.setEnabled(false);
        marital.setEnabled(false);
        active.setEnabled(false);
        deletedButton.setEnabled(false);
        
        
    }//GEN-LAST:event_saveButtonActionPerformed

    private void deletedButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletedButtonActionPerformed
        // TODO add your handling code here:
        
        //get patient ID
        int pID = Integer.parseInt(idField.getText());
        try {
            //connect and prepare delete statement for database
            con = connections.getConnection();
            pst = con.prepareStatement("DELETE FROM patienttable WHERE PatientID=?");
            //set ID equal to ?
            pst.setObject(1, pID);
            //execute the query
            pst.execute();
            
            //terminal at bottom
            System.out.println("Deleted successfully :D");
            java.util.Date date = new java.util.Date();
            console += date + ": Deleted patient successfully :D\n\t---You can now click close.";
            events.setText(console);
            
        } catch(Exception ex) {
            //terminal at bottom
            System.out.println("Failed to delete :(");
            System.err.println(ex.getMessage());
            java.util.Date date = new java.util.Date();
            console += date + ": " + pID + " Failed to delete :(\n";
            events.setText(console);
            
        }
    }//GEN-LAST:event_deletedButtonActionPerformed

    private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButtonActionPerformed
        // TODO add your handling code here:
        
        //set current form visible status to false
        this.setVisible(false);
        //on close, open new Main form with refreshed attributes in case of editing, etc.
        new Main().setVisible(true);
    }//GEN-LAST:event_closeButtonActionPerformed

    private void allergyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_allergyButtonActionPerformed
        // TODO add your handling code here:
        int pID = Integer.parseInt(idField.getText());
        
        AllergyHistoryForm frame2 = new AllergyHistoryForm();
        String change = Integer.toString(pID);
        AllergyHistoryForm.patientID.setText(change);
        
        frame2.setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_allergyButtonActionPerformed

    private void cityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cityActionPerformed

    private void commentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_commentsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_commentsActionPerformed

    private void idFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idFieldActionPerformed

    private void generalMedicalButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generalMedicalButtonActionPerformed
        // TODO add your handling code here:
        
        int pID = Integer.parseInt(idField.getText());
        
        GeneralMed frame5 = new GeneralMed();
        String change = Integer.toString(pID);
        GeneralMed.IDpatient.setText(change);
        
        
        this.setVisible(false);
        frame5.setVisible(true);

    }//GEN-LAST:event_generalMedicalButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PatientDemographicForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PatientDemographicForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PatientDemographicForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PatientDemographicForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PatientDemographicForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JCheckBox active;
    public static javax.swing.JTextField address1;
    public static javax.swing.JTextField address2;
    public static javax.swing.JButton allergyButton;
    public static javax.swing.JTextField citizen;
    public static javax.swing.JTextField city;
    private javax.swing.JButton closeButton;
    public static javax.swing.JTextField comments;
    public static javax.swing.JTextField country;
    public static javax.swing.JButton deletedButton;
    public static javax.swing.JTextField dob;
    public static javax.swing.JButton editButton;
    public static javax.swing.JTextField email;
    public static javax.swing.JTextField emergencyPhone;
    public static javax.swing.JTextField ethnic;
    public static javax.swing.JTextArea events;
    public static javax.swing.JTextField fName;
    public static javax.swing.JTextField gender;
    public static javax.swing.JButton generalMedicalButton;
    public static javax.swing.JTextField hcp;
    public static javax.swing.JTextField idField;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTextField kin;
    public static javax.swing.JTextField kinRelationship;
    public static javax.swing.JTextField lName;
    public static javax.swing.JTextField marital;
    public static javax.swing.JTextField middle;
    public static javax.swing.JButton newButton;
    public static javax.swing.JTextField phone;
    public static javax.swing.JTextField plName;
    public static javax.swing.JButton saveButton;
    public static javax.swing.JTextField ssn;
    public static javax.swing.JTextField state;
    public static javax.swing.JTextField subscriber;
    public static javax.swing.JTextField zip;
    // End of variables declaration//GEN-END:variables
}
